###
POST http://localhost:8080/member/register
Content-Type: application/json

{
  "memberName": "Adam",
  "memberNickname": "서지영지서지영",
  "password" : "1234"
}

###
POST http://localhost:8080/member/login
Content-Type: application/json

{
  "memberName" : "Adam",
  "password" : "1234"
}

###
POST http://localhost:8080/auth/save/community
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBZGFtIiwiYXVkIjoi7ISc7KeA7JiB7KeA7ISc7KeA7JiBIiwibWVtYmVyU3RhdHVzIjoidGFsbCIsInByb2ZpbGVJbWFnZVVybCI6Imh0dHA6Ly9kb29ncmFweXMuY29tL2NvbW1vbi9pbWcvZGVmYXVsdF9wcm9maWxlLnBuZyIsImF1dGgiOiJST0xFX1VTRVIiLCJleHAiOjE2NzA4MDAxODJ9.-sL0S1lzd-_uyOjb4EwYdQOZD1-AVqdGRCTKiGjgyLs

{

}





###
POST http://localhost:8080/auth/board/save
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqaXlvdW5nIiwiYXVkIjoi7LCM7JeJIiwibWVtYmVyU3RhdHVzIjoidmVudGkiLCJwcm9maWxlSW1hZ2VVcmwiOiJodHRwczovL2pheWxpbi1idWNrZXQuczMuYXAtbm9ydGhlYXN0LTIuYW1hem9uYXdzLmNvbS9tZW1iZXJQcm9maWxlSW1hZ2UvZDUxZjJlMzAtY2VkMC00MjM4LWExNzUtOGMyYmE1N2QyMTMxIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY3MDc4NDMwNn0.aDZbXTtHOBhQN7PzyDTGykB2KIpTziJ36A8n-Lx9_LQ
Content-Type: application/json

{

}

###
GET http://localhost:8080/member/auth/mypage/all
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqaXlvdW5nIiwiYXVkIjoi7LCM7JeJIiwibWVtYmVyU3RhdHVzIjoidmVudGkiLCJwcm9maWxlSW1hZ2VVcmwiOiJodHRwczovL2pheWxpbi1idWNrZXQuczMuYXAtbm9ydGhlYXN0LTIuYW1hem9uYXdzLmNvbS9tZW1iZXJQcm9maWxlSW1hZ2UvZDUxZjJlMzAtY2VkMC00MjM4LWExNzUtOGMyYmE1N2QyMTMxIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY3MDc4NDMwNn0.aDZbXTtHOBhQN7PzyDTGykB2KIpTziJ36A8n-Lx9_LQ
Content-Type: application/json

{

}
###
GET http://localhost:8080/board/main
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqaXlvdW5nIiwiYXVkIjoi7LCM7JeJIiwibWVtYmVyU3RhdHVzIjoidmVudGkiLCJwcm9maWxlSW1hZ2VVcmwiOiJodHRwczovL2pheWxpbi1idWNrZXQuczMuYXAtbm9ydGhlYXN0LTIuYW1hem9uYXdzLmNvbS9tZW1iZXJQcm9maWxlSW1hZ2UvZDUxZjJlMzAtY2VkMC00MjM4LWExNzUtOGMyYmE1N2QyMTMxIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY3MDc4NDMwNn0.aDZbXTtHOBhQN7PzyDTGykB2KIpTziJ36A8n-Lx9_LQ
Content-Type: application/json

{

}
###
GET http://localhost:8080/member/auth/mypage/boards?page=1&size=1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqaXlvdW5nIiwiYXVkIjoi7LCM7JeJIiwibWVtYmVyU3RhdHVzIjoidmVudGkiLCJwcm9maWxlSW1hZ2VVcmwiOiJodHRwczovL2pheWxpbi1idWNrZXQuczMuYXAtbm9ydGhlYXN0LTIuYW1hem9uYXdzLmNvbS9tZW1iZXJQcm9maWxlSW1hZ2UvZDUxZjJlMzAtY2VkMC00MjM4LWExNzUtOGMyYmE1N2QyMTMxIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY3MDc4NDMwNn0.aDZbXTtHOBhQN7PzyDTGykB2KIpTziJ36A8n-Lx9_LQ
Content-Type: application/json

{

}

###
POST http://localhost:8080/auth/communityComment/1/create
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqaXlvdW5nIiwiYXVkIjoi7LCM7JeJIiwibWVtYmVyU3RhdHVzIjoidmVudGkiLCJwcm9maWxlSW1hZ2VVcmwiOiJodHRwczovL2pheWxpbi1idWNrZXQuczMuYXAtbm9ydGhlYXN0LTIuYW1hem9uYXdzLmNvbS9tZW1iZXJQcm9maWxlSW1hZ2UvZGNhMDVhNDMiLCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjcwNzk0NDA3fQ.mjNfUlTjiFVWQdwRtL5krV0juIIxLhazkE3bTEVQgtA
Content-Type: application/json

{
  "communityCommentContent": "testing"
}

###
PUT http://localhost:8080/auth/communityComment/9/update
Authorization: Bearer eybGciOiJIUzI1NiJ9.eidWNrZXQuczMuYXAtbm9ydGhlYXN0LTIuYW1hem9uYXdzLmNvbS9tZW1iZXJQcm9maWxlSW1hZ2UvZGNhMDVhNDMiLCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjcwNzk0NDA3fQ.mjNfUlTjiFVWQdwRtL5krV0juIIxLhazkE3bTEVQgtA
Content-Type: application/json

{
  "communityCommentContent": "testing22992"
}


###
DELETE http://localhost:8080/auth/communityComment/9/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBZGFtIiwiYXVkIjoi7ISc7KeA7JiB7KeA7ISc7KeA7JiBIiwibWVtYmVyU3RhdHVzIjoidGFsbCIsInByb2ZpbGVJbWFnZVVybCI6Imh0dHA6Ly9kb29ncmFweXMuY29tL2NvbW1vbi9pbWcvZGVmYXVsdF9wcm9maWxlLnBuZyIsImF1dGgiOiJST0xFX1VTRVIiLCJleHAiOjE2NzA3OTUxNjR9.ScknxZKawKKSsNDFptKPQh-vcYzU5HcJOq2Kl_v11FU
Content-Type: application/json
