###
POST http://localhost:8080/member/register
Content-Type: application/json

{
  "memberName": "Adam3",
  "memberNickname": "뽈깡뽈낑",
  "password" : "1234"
}

###
POST http://localhost:8080/member/login
Content-Type: application/json

{
  "memberName" : "Adam3",
  "password" : "1234"
}

###
GET http://localhost:8080/member/name/check/Adam1
Content-Type: application/json



###
GET http://localhost:8080/member/nickname/check
Content-Type: application/json

{
  "memberNickname": "뽈깡뽈낑"
}
###
POST http://localhost:8080/auth/board/save
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBZGFtIiwiYXVkIjoi672I6rmh672I64KRIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY5OTg5NTA5NH0.azNNZE5xBEUkqEagqlaLDQ3El-Zyk7YrJwufitXVVXo

{
}

###
POST http://localhost:8080/auth/rating/1
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBZGFtIiwiYXVkIjoi7JWX7ZWoIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY5OTc3NDQ1Nn0.YQWSQi9gzyowC_SNlvF0L922AsL2gfyv3el-0nb-3Jg

{
  "coffeeRate": 4,
  "dessertRate": 3,
  "priceRate": 4,
  "kindnessRate": 5,
  "moodRate": 5,
  "parkingRate": 5
}
